bri = set(['brazil', 'russia', 'india'])
print(bri)
print('india' in bri)
print('indian' in bri)
bric = bri.copy()
bric.add('china')
print(bric)
print(bric.issuperset(bri))
bri.remove('russia')
print(bri)
print(bric & bri)
print(bric | bri)
