a_set = {1, 23, 3}
print(a_set)
a_set.add(4)
print(a_set)
a_set.update({5, 6})
print(a_set)
a_set.update({-2, 9}, {66, 7})
print(a_set)
a_set.update([55, 77])
print(a_set)
a_set.update((00, 11, 22))
print(a_set)
a_set.discard(66)
print(a_set)
a_set.discard(66)
print(a_set)
a_set.remove(9)
print(a_set)
print(type(a_set))
print(a_set.pop())
b_set = a_set.copy()
print(b_set)
a_set.clear()
print(a_set)
a_set = {8, 6}
print(a_set)
print(8 in a_set)
a_set.union(b_set)
print(a_set)
print(b_set)
union_set = b_set.union(a_set)
print(union_set)
intersection_set = a_set.intersection(b_set)
print(intersection_set)
difference_set = a_set.difference(b_set)
print(difference_set)
symmetric_difference_set = a_set.symmetric_difference(b_set)
print(symmetric_difference_set)
c_set = {11, 22, 23}
print(b_set.issuperset(c_set))
print(c_set.issuperset(b_set))
print(c_set.issubset(b_set))
x_set = set([5, 3])
print(x_set)
y_set = set((78, 9))
print(y_set)
